import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { 
  FireIcon, 
  ShieldCheckIcon, 
  SparklesIcon,
  ArrowRightIcon,
  PlayIcon,
  CheckCircleIcon,
  CpuChipIcon,
  HeartIcon,
  TrophyIcon
} from '@heroicons/react/24/outline'

export default function LandingPage({ onGetStarted }) {
  const [currentFeature, setCurrentFeature] = useState(0)
  const [isVisible, setIsVisible] = useState(false)

  const features = [
    {
      Icon: CpuChipIcon,
      title: "AI-Powered Workouts",
      description: "Get personalized workout plans generated by advanced AI that adapts to your goals and fitness level.",
      color: "text-red-400"
    },
    {
      Icon: ShieldCheckIcon,
      title: "Equipment-Based Training",
      description: "Workout plans tailored to your available equipment, from bodyweight to full gym setups.",
      color: "text-blue-400"
    },
    {
      Icon: TrophyIcon,
      title: "Progress Tracking",
      description: "Track your fitness journey with detailed progress reports and achievement milestones.",
      color: "text-yellow-400"
    },
    {
      Icon: HeartIcon,
      title: "Health-Focused",
      description: "Safe, effective workout plans designed by fitness experts with your health in mind.",
      color: "text-green-400"
    }
  ]

  const benefits = [
    "Personalized AI workout generation",
    "Equipment-specific training plans", 
    "Multiple fitness levels from beginner to expert",
    "Track progress and achievements",
    "Safe and effective exercise routines",
    "Adaptable to your schedule"
  ]

  useEffect(() => {
    setIsVisible(true)
    const interval = setInterval(() => {
      setCurrentFeature((prev) => (prev + 1) % features.length)
    }, 4000)
    return () => clearInterval(interval)
  }, [])

  const renderFeatureIcon = (IconComponent, color) => {
    return <IconComponent className={`w-8 h-8 ${color}`} />
  }

  const handleGetStartedClick = () => {
    if (onGetStarted) {
      onGetStarted()
    }
  }

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.2
      }
    }
  }

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: {
        type: "spring",
        stiffness: 100,
        damping: 10
      }
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 overflow-hidden">
      {/* Animated Background */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-red-500/20 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-blue-500/20 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '2s' }}></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '4s' }}></div>
      </div>

      {/* Navigation */}
      <nav className="relative z-10 px-6 py-4 bg-gray-900/50 backdrop-blur-lg border-b border-gray-800/50">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-red-500/10 border border-red-500/30">
              <FireIcon className="h-6 w-6 text-red-400" />
            </div>
            <span className="text-xl font-bold text-white uppercase tracking-wider">FitForge</span>
          </div>
          <button
            onClick={handleGetStartedClick}
            className="px-6 py-2 bg-red-500 text-white rounded-lg font-semibold hover:bg-red-600 transition-all duration-300 transform hover:scale-105"
          >
            Get Started
          </button>
        </div>
      </nav>

      {/* Hero Section */}
      <motion.div 
        className="relative z-10 max-w-7xl mx-auto px-6 py-20"
        variants={containerVariants}
        initial="hidden"
        animate={isVisible ? "visible" : "hidden"}
      >
        <div className="text-center space-y-8">
          {/* Badge */}
          <motion.div variants={itemVariants} className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-red-500/10 border border-red-500/30">
            <SparklesIcon className="w-4 h-4 text-red-400" />
            <span className="text-sm text-red-400 font-semibold">AI-Powered Fitness</span>
          </motion.div>

          {/* Main Heading */}
          <motion.h1 variants={itemVariants} className="text-5xl md:text-7xl font-bold text-white leading-tight">
            Welcome to
            <span className="block text-transparent bg-clip-text bg-gradient-to-r from-red-400 to-orange-400">
              FitForge
            </span>
          </motion.h1>

          {/* Subheading */}
          <motion.p variants={itemVariants} className="text-xl text-gray-300 max-w-3xl mx-auto leading-relaxed">
            Transform your fitness journey with AI-generated workout plans tailored to your goals, 
            equipment, and fitness level. No more guessing - just smart, effective workouts designed for you.
          </motion.p>

          {/* CTA Buttons */}
          <motion.div variants={itemVariants} className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <button
              onClick={handleGetStartedClick}
              className="group px-8 py-4 bg-gradient-to-r from-red-500 to-orange-500 text-white rounded-xl font-bold text-lg hover:from-red-600 hover:to-orange-600 transition-all duration-300 transform hover:scale-105 shadow-lg hover:shadow-red-500/25 flex items-center gap-3"
            >
              <PlayIcon className="w-5 h-5" />
              Get Started Free
              <ArrowRightIcon className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </button>
            
            <div className="flex items-center gap-2 text-gray-400">
              <CheckCircleIcon className="w-5 h-5 text-green-400" />
              <span className="text-sm">No credit card required</span>
            </div>
          </motion.div>
        </div>

        {/* Feature Showcase */}
        <motion.div variants={itemVariants} className="mt-20 relative">
          <div className="bg-gray-800/50 backdrop-blur-lg rounded-2xl p-8 border border-gray-700/50">
            <AnimatePresence mode="wait">
              <motion.div
                key={currentFeature}
                initial={{ opacity: 0, x: 50 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -50 }}
                transition={{ duration: 0.5 }}
                className="flex items-center gap-6"
              >
                <div className={`p-4 rounded-xl bg-gradient-to-br ${features[currentFeature].color.includes('red') ? 'from-red-500/20 to-orange-500/20' : features[currentFeature].color.includes('blue') ? 'from-blue-500/20 to-cyan-500/20' : features[currentFeature].color.includes('yellow') ? 'from-yellow-500/20 to-orange-500/20' : 'from-green-500/20 to-emerald-500/20'}`}>
                  {renderFeatureIcon(features[currentFeature].Icon, features[currentFeature].color)}
                </div>
                <div className="flex-1">
                  <h3 className="text-2xl font-bold text-white mb-2">{features[currentFeature].title}</h3>
                  <p className="text-gray-300">{features[currentFeature].description}</p>
                </div>
              </motion.div>
            </AnimatePresence>

            {/* Feature Indicators */}
            <div className="flex justify-center gap-2 mt-6">
              {features.map((_, index) => (
                <button
                  key={index}
                  onClick={() => setCurrentFeature(index)}
                  className={`w-2 h-2 rounded-full transition-all duration-300 ${
                    index === currentFeature 
                      ? 'bg-red-400 w-8' 
                      : 'bg-gray-600 hover:bg-gray-500'
                  }`}
                />
              ))}
            </div>
          </div>
        </motion.div>
      </motion.div>

      {/* Benefits Section */}
      <motion.div 
        className="relative z-10 max-w-7xl mx-auto px-6 py-20"
        variants={containerVariants}
        initial="hidden"
        animate={isVisible ? "visible" : "hidden"}
      >
        <motion.div variants={itemVariants} className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
            Everything You Need to Succeed
          </h2>
          <p className="text-xl text-gray-300 max-w-2xl mx-auto">
            Our AI-powered platform provides all the tools and guidance you need for your fitness journey.
          </p>
        </motion.div>

        <motion.div variants={itemVariants} className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {benefits.map((benefit, index) => (
            <motion.div
              key={index}
              variants={itemVariants}
              whileHover={{ scale: 1.02 }}
              className="flex items-center gap-3 p-4 bg-gray-800/50 backdrop-blur-lg rounded-xl border border-gray-700/50 hover:border-red-500/30 transition-all duration-300"
            >
              <CheckCircleIcon className="w-5 h-5 text-green-400 flex-shrink-0" />
              <span className="text-gray-200">{benefit}</span>
            </motion.div>
          ))}
        </motion.div>
      </motion.div>

      {/* Final CTA */}
      <motion.div 
        className="relative z-10 max-w-4xl mx-auto px-6 py-20"
        variants={containerVariants}
        initial="hidden"
        animate={isVisible ? "visible" : "hidden"}
      >
        <motion.div 
          variants={itemVariants}
          className="bg-gradient-to-r from-red-500/20 to-orange-500/20 backdrop-blur-lg rounded-2xl p-12 border border-red-500/30 text-center"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
            Ready to Transform Your Fitness?
          </h2>
          <p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">
            Join thousands of users who have already discovered the power of AI-generated workout plans. 
            Start your journey today and see results faster than ever before.
          </p>
          <button
            onClick={handleGetStartedClick}
            className="px-8 py-4 bg-gradient-to-r from-red-500 to-orange-500 text-white rounded-xl font-bold text-lg hover:from-red-600 hover:to-orange-600 transition-all duration-300 transform hover:scale-105 shadow-lg hover:shadow-red-500/25 flex items-center gap-3 mx-auto"
          >
            <TrophyIcon className="w-5 h-5" />
            Start Your Journey
            <ArrowRightIcon className="w-5 h-5" />
          </button>
        </motion.div>
      </motion.div>

      {/* Footer */}
      <footer className="relative z-10 px-6 py-8 border-t border-gray-800/50">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center gap-2 mb-4">
            <FireIcon className="w-5 h-5 text-red-400" />
            <span className="text-white font-semibold">FitForge</span>
          </div>
          <p className="text-gray-400 text-sm">
            © 2026 FitForge. Your AI-powered fitness companion.
          </p>
        </div>
      </footer>
    </div>
  )
}
